repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        args: ["check"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
        args: ["--check"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-PyYAML>=6.0.12.12"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
